In [1]:
import pandas as pd

In [32]:
btp = pd.read_excel('../data/btp.xlsx')

In [33]:
btp['no_eks'] = btp['no_eks'].astype('int')
btp['flag_aktif'] = btp['flag_aktif'].astype('int')
btp[:10]

,id_publikasi,Judul,no_eks,kd_ruang,lorong,rak,baris,flag_aktif,Box Tujuan,box_num
0,123.1217.2051,INDEKS TENDENSI KONSUMEN SULAWESI UTARA 2016,1,3,GA,1,4,1,BTP78,78
1,224.0914.0751,BULLETIN OF STATISTICS ON WORLD TRADE IN ENGIN...,1,3,LN,5,4,1,BTP70,70
2,122.0119.0029,STATISTIK DAERAH PROVINSI SULAWESI TENGGARA 2018,1,3,GB,3,1,1,BTP 13,13
3,122.1217.2762,STATISTIK DAERAH PROVINSI MALUKU UTARA 2016,1,3,GB,1,3,1,BTP 13,13
4,123.0118.0466,KEMISKINAN PROVINSI SULAWESI TENGGARA 2006-2016,1,3,GB,3,1,1,BTP 13,13
5,123.0118.0481,INDEKS TENDENSI KONSUMEN SULAWESI TENGGARA TAH...,1,3,GB,3,1,1,BTP 13,13
6,123.0118.0489,DIREKTORI DESA PROVINSI SULAWESI TENGGARA 2016,1,3,GB,3,1,1,BTP 13,13
7,123.0118.0490,INDIKATOR KESEJAHTERAAN RAKYAT PROVINSI SULAWE...,1,3,GB,3,1,1,BTP 13,13
8,123.0119.0548,INDEKS TENDENSI KONSUMEN PROVINSI SULAWESI TEN...,1,3,GB,3,1,1,BTP 13,13
9,123.0119.1271,STATISTIK PENDIDIKAN PROVINSI SULAWESI TENGGAR...,1,3,GB,3,1,1,BTP 13,13

In [34]:
txt = []
data = btp.copy()
for i in range(len(data)):
    txt.append(
        f"('{data['id_publikasi'].iloc[i]}',{data['no_eks'].iloc[i]},'{data['box_num'].iloc[i]}')")

In [35]:
page = 1
for page in range(1,8):
    txt2 = ",".join(txt[(page-1)*1000:page*1000])
    txt_file = open(f'../data/btp_{page}.txt','w')
    txt_file.write(txt2)
    txt_file.close()